name: Manual Nginx Deployment
on:
  workflow_dispatch:

jobs:
  deploy-nginx:
    runs-on: ubuntu-latest
    steps:
      - name: Start Nginx Container
        run: |
          docker run -d -p 80:80 nginx:latest
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Verify Nginx is running
        run: |
          curl http://localhost:80 || exit 1

      - name: Run Playwright tests
        run: npx playwright test